comment/urls.py
from unicodedata import name
from django.urls import path, re_path
from . import views


app_name = "comment"

urlpatterns = [
    # re_path(r"add/", views.user_comment, name="user_comment"),
    re_path(r"detail/(?P<article_id>\d+)", views.article_detail, name="article_detail"),
    path('comment_control/',views.comment_control,name='comment_control')
]

commonly/urls.py
from django.urls import path, re_path
from . import views
import commonly

app_name = 'commonly'

urlpatterns = [
    path(r"index/", views.index, name="index"),
    re_path(r"index/(?P<article_id>\d+)/$", views.article_like, name="article_like"),
]

cuser/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cuser'

urlpatterns = [
    path(r"cuser/detail_profile/",views.detail_profile,name="detail_profile"),
]

project_forum/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from commonly import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/commonly/index/')),
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),  #设置进入默认index界面
    path('accounts/', include('allauth.urls')),
    path('accounts/',include('cuser.urls',namespace='cuser')),
    path('commonly/', include('commonly.urls', namespace='commonly')),
    path('theme/',include('theme.urls',namespace='theme')),
    path('comment/',include('comment.urls',namespace='comment')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/urls.py
from unicodedata import name
from django.urls import path, re_path
from . import views

app_name = "theme"

urlpatterns = [
    path(r"article_theme_add/", views.article_theme_add, name="article_theme_add"),
    path(r"article_publish/", views.article_publish, name="article_publish"),
    re_path(r"author_articles/(?P<author_id>\d+)/$", views.author_articles, name="author_articles"),
    re_path(r"theme_details/(?P<at_id>\d+)/$", views.theme_details, name="theme_details"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'js/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/comment.css' %}">
<link rel="stylesheet" href="{% static 'css/author_article.css'%}">
<link rel="stylesheet" href="{% static 'css/navigation.css'%}">
<link rel="stylesheet" href="{% static 'css/base.css'%}">

<html lang="en">

    <head>
    <meta charset="UTF-8">
        <title>Forum NullPointer --
            {% block title_block %}
                default sub title
            {% endblock %}
        </title>
    </head>

    <body >
        <!-- <img src="/static/img/bizhi.gif" id="bizhi"> -->
        <div class="container" id="navigation_div">
            <nav class="navbar navbar-default" id="navigation">
                <div class="container-fluid">
                    <img class="img-circle" src="{% static 'img/logo.jpg'%}" alt="Logo">
                    <ul class="nav navbar-nav navbar-right">
                    {% if request.path == "/commonly/index/" %}
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'theme:author_articles' request.user.id %}" title="search user profile">
                            User：{% firstof request.user.username %}</a>
                        </li>
                        <li><a href="" data-toggle="modal" data-target="#chuangjianzhuanti">CreateTheme</a>
                        </li>
                        <li><a href="{% url 'theme:article_publish' %}">Publish</a></li>
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                        <li><a href="{% url 'account_signup' %}">Register</a></li>
                        {% endif %}
                    {% else %}
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'theme:author_articles' request.user.id %}" title="search user profile">
                            User：{% firstof request.user.username %}</a>
                        </li>
                        <li><a href="{% url 'commonly:index' %}">IndexPage</a>
                        </li>
                        <li><a href="{% url 'theme:article_publish' %}">Publish</a></li>
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}">Login</a></li>
                        <li><a href="{% url 'account_signup' %}">Register</a></li>
                        {% endif %}
                  {% endif %}
                    </ul>
                </div>
            </nav>
        </div>

        {% block body_block %}
            Default content of block
        {% endblock %}

        <!--

            <footer>
                <p>&copy; Internet Technology Team10 &middot; <a href=" ">Privacy</a > &middot;
                    <a href="#">Terms</a ></p >
                    </footer>
        
        -->

    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title_block %}
    index page
{% endblock %}



{% block body_block %}



    <div class="container">
    <div class="row">

    <div class="panel panel-default content_list col-md-8" style="margin-left: 15px;">
                <div class="panel-body">
                    {% for single_article in all_article %}
                    <div class="media article" >
                        <div class="media-body">
                            <h4 class="media-heading"><a href="{% url 'comment:article_detail' single_article.article_id %}">{{single_article.article_title}}</a></h4>
                            <p>{{single_article.article_content|truncatechars:300}}...</p>
                            <div>
                                <span><a href="{% url 'theme:author_articles' single_article.article_author.id %}">User: {{single_article.article_author.username}}</a></span>
                            </div>
                            <div>
                                <span><a href="{% url 'comment:article_detail' single_article.article_id %}">Comment: {{single_article.count_all_commented}}</a></span> 
                                <span><a href="{% url 'commonly:article_like' single_article.article_id %}">like: {{single_article.count_all_liked}}</a></span>
                            </div>
                        </div>
                    <hr/>
                    </div>
                    {% endfor %}  
        </div>
    </div>
   
    <div class="panel panel-group panel-default col-md-3" id="hot_theme" style="margin-top: 8px;margin-left: 50px;">
        <div class="panel-heading">
            <h3>Themes</h3>
        </div>
        <ul class="list-group">
            {% for single_themes in all_themes %}
            <li class="list-group-item">
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="/media/{{ single_themes.at_cover }}"
                                 alt="..." style="height: 30px;width: 30px">
                        </a>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading"><a href="{% url 'theme:theme_details' single_themes.at_id %}">{{single_themes.at_name}}</a></h3>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>

    
</div>

</div>
{#    chaungjianzhuanti#}
<div id="chuangjianzhuanti" class="modal fade bs-subject-modal-sm" aria-labelledby="theme">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create Theme</h4>
            </div>
            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="{% url 'theme:article_theme_add' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="s_name" class="col-sm-3 control-label">Theme Name</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" name="at_name" id="s_name" placeholder="Theme Name">
                        </div>
                    </div>
                    <input type="hidden" name="at_author" value="{{ request.user.id}}">
                    <div class="form-group">
                        <label for="as_cover" class="col-sm-3 control-label">Theme cover</label>
                        <div class="col-sm-6">
                            <input type="file" name="at_cover" id="as_cover" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>
    <script src="{% static 'js/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap/js/bootstrap.js' %}"></script>

{% endblock %}