comment/urls.py
from unicodedata import name
from django.urls import path, re_path
from . import views


app_name = "comment"

urlpatterns = [
    # re_path(r"add/", views.user_comment, name="user_comment"),
    re_path(r"detail/(?P<article_id>\d+)", views.article_detail, name="article_detail"),
    path('comment_control/',views.comment_control,name='comment_control')
]

commonly/urls.py
from django.urls import path, re_path
from . import views
import commonly

app_name = 'commonly'

urlpatterns = [
    path(r"index/", views.index, name="index"),
    re_path(r"index/(?P<article_id>\d+)/$", views.article_like, name="article_like"),
]

cuser/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cuser'

urlpatterns = [
    path(r"cuser/detail_profile/",views.detail_profile,name="detail_profile"),
]

project_forum/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from commonly import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/commonly/index/')),
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),  #设置进入默认index界面
    path('accounts/', include('allauth.urls')),
    path('accounts/',include('cuser.urls',namespace='cuser')),
    path('commonly/', include('commonly.urls', namespace='commonly')),
    path('theme/',include('theme.urls',namespace='theme')),
    path('comment/',include('comment.urls',namespace='comment')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/urls.py
from unicodedata import name
from django.urls import path, re_path
from . import views

app_name = "theme"

urlpatterns = [
    path(r"article_theme_add/", views.article_theme_add, name="article_theme_add"),
    path(r"article_publish/", views.article_publish, name="article_publish"),
    re_path(r"author_articles/(?P<author_id>\d+)/$", views.author_articles, name="author_articles"),
    re_path(r"theme_details/(?P<at_id>\d+)/$", views.theme_details, name="theme_details"),
]

comment/models.py
from django.db import models
from django.contrib.auth.models import User
from theme.models import Article

# Create your models here.
class Comment(models.Model):
    article = models.ForeignKey(verbose_name="belong to which article", to=Article, on_delete=models.CASCADE)
    comment_id = models.AutoField(verbose_name="comment id", primary_key=True)
    comment_text = models.TextField()
    comment_time = models.DateTimeField(auto_now_add=True)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    count_all_liked = models.IntegerField(verbose_name="how many person liked", default=0)
    count_all_collected = models.IntegerField(verbose_name="how many person collected", default=0)
    pre_comment = models.ForeignKey('self',on_delete=models.DO_NOTHING,null=True,verbose_name='father_id')  #if no father set to NULL, "self"foreign to self

    def save(self, *args, **kwargs):
        if len(self.comment_text) <= 0 or self.comment_text.isspace():
            self.comment_text = "invalid comment input"
        super(Comment, self).save(*args, **kwargs)

theme/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Artheme(models.Model):
    """theme"""
    at_id = models.AutoField(verbose_name="theme id", primary_key=True)
    at_author = models.ForeignKey(verbose_name="belong to which user", to=User, on_delete=models.CASCADE)
    at_name = models.CharField(verbose_name="theme name", max_length=50)
    at_count = models.IntegerField(verbose_name="have how many articles", default=0)
    at_cover = models.ImageField(verbose_name="theme cover picture", upload_to="upload/theme/")
    authors = models.ManyToManyField(verbose_name="which user subscribed", to=User, related_name="article_theme")

    def save(self, *args, **kwargs):
        if self.at_count < 0:
            self.at_count = 1
        super(Artheme, self).save(*args, **kwargs)


class Article(models.Model):
    """article"""
    article_id = models.AutoField(verbose_name="article id", primary_key=True)
    article_author = models.ForeignKey(verbose_name="belong to which user", to=User, on_delete=models.CASCADE)
    article_theme = models.ForeignKey(verbose_name="belong to which theme", to=Artheme, on_delete=models.CASCADE)
    article_content = models.TextField(verbose_name="publish content")
    publish_time = models.DateField(verbose_name="publish time", auto_now_add=True)
    article_title = models.CharField(verbose_name="article title", max_length=200)
    article_img = models.ImageField(verbose_name="article cover image", upload_to="upload/ar/", default="/media/upload/ar/moren.jpg")

    count_all_liked = models.IntegerField(verbose_name="how many person liked", default=0)
    count_all_collected = models.IntegerField(verbose_name="how many person collected", default=0)
    count_all_commented = models.IntegerField(verbose_name="how many person commented", default=0)
    count_all_words = models.IntegerField(verbose_name="count article words", default=0)

    def save(self, *args, **kwargs):
        if self.count_all_commented < 0:
            self.count_all_commented = 1
        super(Article, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.article_title + "-" + self.article_content

class like(models.Model):
    """like"""
    like_id = models.AutoField(verbose_name="like id", primary_key=True)
    like_poster_id = models.IntegerField(verbose_name="like poster id")
    like_article_id = models.IntegerField(verbose_name="liked article")


comment/views.py
from pydoc import resolve
from django.http import JsonResponse
from django.shortcuts import render, redirect, resolve_url
from .models import Comment
from django.urls import reverse
from django.contrib import messages

# Create your views here.


from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from theme.models import Article


# def user_comment(request):
#
#     return render(request,"article/publish_ar_detail.html")

def article_detail(request, article_id):
    article = Article.objects.get(pk=article_id)
    comment_list = Comment.objects.filter(article_id = article_id)
    context = {
        'article' : article,
        'comment_list' : comment_list
    }
    return render(request, "article/publish_ar_detail.html", context=context)

@login_required
@csrf_exempt
def comment_control(request): 
    if request.user.username:
        comment_user = request.user
        comment_text = request.POST.get('text','')

        article_id = request.POST.get('article_id')
        article = Article.objects.filter(article_id = article_id)[0]

        if len(comment_text) == 0 or comment_text.isspace() :
            print('invalied comment inputs')
            messages.error(request,"Please enter valid content!")
            return redirect('/comment/detail/'+ article_id)

        pid = request.POST.get('pid')
        Comment.objects.create(comment_text=comment_text,pre_comment_id=pid,article_id=article_id,comment_user=comment_user)

        # show the comment
        article.count_all_commented = Comment.objects.filter(article = article).count()
        article.save()

        print('Valid inputs')
        # article = list(Comment.objects.values('comment_id','comment_text','pre_comment_id','article_id','comment_user','comment_time'))
        return redirect('/comment/detail/'+ article_id)
    #else:
    #    return redirect('/user_login/')

templates/article/author_article.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}
    Forum_Author_Article
{% endblock %}


{% block body_block %}

    <div class=".container ">
        <div class="row authors_ar">
            <div class="col-lg-10 col-lg-offset-1" >
                
                <h3><label>Author: </label>&nbsp;{% firstof author.username %}</h3>
                

            </div>
        </div>

            <div class="tab-content col-lg-10 col-lg-offset-1">
                <div role="tabpanel" class="tab-pane active">
                    {% if isUser %}
                    <h4><a href="{% url 'cuser:detail_profile' %}">modify user profile</a></label></h4>
                    {% endif %}

                    <h4><label>liked article: </h4>
                    <div class="panel panel-default" >
                        <div class="panel-body">
                            {% for single_article in likesArticle %}
                            <div class="media article" >
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="{% url 'comment:article_detail' single_article.article_id %}">{{single_article.article_title}}</a></h4>
                                </div>
                            </div>
                            {% endfor %}  
                        </div>
                    </div>

                    <hr/>

                    <h4><label>posted article: </h4>                   
                    <div class="panel panel-default" >
                        <div class="panel-body">
                        {% for single_article in author.article_set.all %} 
                        <h4 class="panel-title ar_title">
                            <a href="{% url 'comment:article_detail' single_article.article_id %}">{{ single_article.article_title }}</a>
                        </h4>
                        
                        <div class="panel-body ar_content">
                            <p class="ar_content_detail">{{ single_article.article_content}}</p>
                            <div class="buttom_set">
                                <span>Author: {% firstof single_article.article_author.username %}</span>
                                <span>Comment: {{ single_article.count_all_commented }}</span>
                                <span>like: {{ single_article.count_all_liked }}</span>
                            </div>
                        </div>
                    <hr/>
                    
                    {% empty %}
                    <div>
                        <p>No any articles</p>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>


   


    <script src="{% static 'js/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap/js/bootstrap.js' %}"></script>
{% endblock %}

templates/article/comment.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'js/bootstrap/css/bootstrap.css' %}">
<html>
    <head>
        <title>comment</title>
    </head>
<body>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="comment_area" style="margin-top:2em; border: 1px dashed; padding: 2em;">
                <h3 class = "comment_area_list">提交评论区域</h3>
                {% if user.is_authenticated %}
                    {{user.username}} 已登录
                    <form method="POST" action="{% url 'theme:comment' %}">
                        {% csrf_token %}
                        <textarea name="text" id="comment_text" placeholder="提交评论"></textarea>
                        <!-- <input type="hidden" name="comment_article" value=""> -->
                        <input type="submit" name="submit" value="comment"/>
                    </form>
                {% else %}
                    未登录
                {% endif %}
                <div style="margin-top:2em; border: 1px dashed; padding: 2em;">
                    <h3>评论列表</h3>
                    {% for comment in comments %}
                        <div>
                            {{comment.comment_user.username}}
                            {{comment.comment_time|date:"Y-m-d H:n:s"}}:
                            {{comment.comment_text}}
                        </div>
                    {% empty %}
                        没评论
                    {% endfor %}
                    </div>

            </div>
        </div>
    </div>
   
</body>

</html>

templates/article/publish_ar.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Edit Content</title>
    <link rel="stylesheet" href="{% static 'js/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'js/editor_md/css/editormd.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="form-group col-md-3">
                <input type="hidden" id="who_publish" value="{{request.user.id}}">
                <div>
                    <span>Input Title</span>
                    <span><input type="text" id="publish_title" class="form-control" placeholder="input title here"></span>
                </div>
                <div>
                    <span>Choose Theme</span>
                    <select name="article_theme" id="theme"  class="form-control">
                    {% for single_theme in article_theme_list %}
                    <option value="{{single_theme.at_id}}">{{single_theme.at_name}}</option>
                    {% endfor %}
                </select>
                </div>
            </div>
            <div class="col-md-2">
                <button class="btn btn-default" id="publish" style="margin-top: 25px;" href="{% url 'commonly:index' %}">Go publish</button>
            </div>
        </div>
        <div class="row">
            <div id="test-editormd">
                <textarea style="display:none;"></textarea>
            </div>
        </div>
    </div>



<script src="{% static 'js/jquery/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'js/editor_md/editormd.js' %}"></script>
<script src="{% static 'js/editor_md/clipboard.js' %}"></script>

<script>
    var getcontent;
    $(function () {
        getcontent = editormd("test-editormd", {
            width: "90%",
            height: 500,
            path: "{% static 'js/editor_md/lib/' %}",
            syncScrolling: "single",
            imageUpload : true,
            imageFormats : ["jpg", "jpeg", "png","gif"],
            onload: function () {
                initPasteDragImg(this);
            }
        });

        $("#publish").click(function() {
            let publish_title = $("#publish_title").val();
            let publish_content = getcontent.getMarkdown();
            let publish_author_id = $("#who_publish").val();
            let publish_theme_id = $("#theme").val();

            $.ajax({
                url: "{% url 'theme:article_publish' %}",
                type: "POST",
                data: {
                    "article_title": publish_title,
                    "article_content": publish_content,
                    "article_author": publish_author_id,
                    "article_theme": publish_theme_id
                },
                success: function(resp) {
                    let res = confirm("publish successful")
                    if(res) {
                        window.location = '/commonly/index/';
                    }
                },
                error: function(resp) {
                    console.log("error");
                }
            });
        })
    });
</script>
</body>
</html>

templates/article/publish_ar_detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title_block %}
    Detail and comment page of {{ article_object.article_title }}
{% endblock %}


{% block body_block %}

    <div class="container article_detail_container col-lg-10 col-lg-offset-1" >
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 >Title : {{ article.article_title }}</h3></div>
                <div class="panel-body">
                    <p>Content : {{ article.article_content }}</p>
                </div>
                <div class="panel-footer">
                    <span >Article Publish Time : {{ article.publish_time }}</span>
                    <span class="col-lg-offset-1">Author : {{ article.article_author }}</span>
                    
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-xs-13 col-xs-offset-0">
                <div class="panel panel-body">
                <div class="comment_area">
                    <h3 class = "comment_area_list">Comment submit area</h3>
                    {% if user.is_authenticated %}
                        {{user.username}} already login
                        <form method="POST" action="{% url 'comment:comment_control' %}" name="commentForm">
                            {% csrf_token %}
                            <textarea name="text" id="comment_text" placeholder="please submit comment here"></textarea>
                            <input type="hidden" name="article_id" value="{{ article.article_id }}">
                            <input type="hidden" name="pid" value="{{ comment.pre_comment_id }}">
                            <input type="submit" name="submit" value="comment" id="submit"/>
                        </form>
                    {% else %}
                        HAVEN'T LOG IN
                    {% endif %}
                    <div id="comment_list">
                        <h3>Comment Lists</h3>
                        {% for comment in comment_list %}
                        <div>
                            <h5>The {{ forloop.counter}} floor -> By:{{ comment.comment_user.username }} -> {{ comment.comment_time }} -> 
                                <button class="reply btn btn-default" username={{ comment.comment_user.username }} pk={{ comment.pk }}>Reply</button>
                            </h5> 
                            {% if comment.pre_comment_id %} 
                                <h6>Comment Text:{{ comment.pre_comment.comment_content }}</h6> 
                            {% endif %}
                            <p>Comment Text:{{ comment.comment_text }}</p>
                            <hr>
                        </div>
                        {% empty %}
                            Comment null
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    </div>


<script src="{% static 'js/jquery/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'js/editor_md/clipboard.js' %}"></script>

<script>
    var pid = ""
    $(".comment_post submit submit").click(function (){
        $.ajax({
            url: 'comment/comment_control',
            typy: 'POST',
            data: {
                'comment_text': $("#comment_text").val(),
                'article_id': article_id,
                'pid': pid
            },
            success: function (res){
                    console.log(res)
                    $("#comment_content").val("")
                    pid = ""                      

                }
        })

    })
    $(".reply").click(function (){
            $("#comment_text").focus()
            var val = "@" + $(this).attr("username") + "\n"
            $("#comment_text").val(val)
            pid = $(this).attr("pk")
    })
</script>


{% endblock %}

templates/article/theme_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}
    index page
{% endblock %}



{% block body_block %}

<div class=".container ">
    <div class="row authors_ar">
        <div class="col-lg-10 col-lg-offset-1" >
            
            <h3><label>Theme owner: </label>&nbsp;{{ owner.username }}</h3>
            
        </div>
    </div>

        <div class="tab-content col-lg-10 col-lg-offset-1">
            <div role="tabpanel" class="tab-pane active">
                <h4><label>Articles posted: </h4>                   
                <div class="panel panel-default" >
                    <div class="panel-body">
                    {% for single_article in theme_articles %} 
                    <h4 class=".content_list .media .media-body .media-heading">
                        <a href="{% url 'comment:article_detail' single_article.article_id %}">{{ single_article.article_title }}</a>
                    </h4>
                    
                    <div class="panel-body ar_content">
                        <p class="ar_content_detail">{{ single_article.article_content }}</p>
                        <div class="buttom_set">
                            <span><a href="{% url 'comment:article_detail' single_article.article_id %}">Comment: {{ single_article.count_all_commented }}</a></span>
                            <span><a href="{% url 'commonly:article_like' single_article.article_id %}">like: {{ single_article.count_all_liked }}</a></span>
                        </div>
                    </div>
                <hr/>
                
                {% empty %}
                <div>
                    <p>No article</p>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</div>

<script src="{% static 'js/jquery/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap/js/bootstrap.js' %}"></script>

{% endblock %}